//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banking_system_be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public Nullable<long> AadharNo { get; set; }
        public string PanCard { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string AccountType { get; set; }
        public string PhoneNo { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> InitialAmount { get; set; }
        public Nullable<int> IsActive { get; set; }
    }
}
