//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banking_system_be.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int ID { get; set; }
        public string FromAccount { get; set; }
        public string ToAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    }
}
